name: Check inochi-creator release

on:
#  schedule: # for scheduling to work this file must be in the default branch
#  - cron: "0 * * * *" # run every hour
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 

env:
  FLATPAK_ID: com.inochi2d.inochi-creator

jobs:
  release-check:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08

    steps:
      - uses: actions/checkout@v3
      - name: Fix git
        run: |
          git config --global --add safe.directory /__w/${{ env.FLATPAK_ID }}/${{ env.FLATPAK_ID }}

      - name: Check updates
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        with:
          args: --edit-only ./${{ env.FLATPAK_ID }}.yml

      - name: Check changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
            exit 1
          fi

      - name: Install deps
        run: |
          dnf -y install dub ldc python3-pyyaml

      - name: Update dependencies
        run: |
          ./update-dependencies.sh

      - name: Reset yml
        run: |
          git checkout -- ${FLATPAK_ID}.yml

      - name: Recheck and open PR
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork ${{ env.FLATPAK_ID }}.yml
