name: Check inochi-creator release

on:
#  schedule: # for scheduling to work this file must be in the default branch
#  - cron: "0 * * * *" # run every hour
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 

env:
  FLATPAK_ID: com.inochi2d.inochi-creator

jobs:
  inochi-creator-release-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check updates
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        with:
          args: --edit-only ./${{ env.FLATPAK_ID }}.yml

      - name: Check changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
            exit 1
          fi

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
          dub: "1.29.0"

      - name: Update dependencies
        run: |
          ./update-dependencies.sh

      - name: Reset yml
        run: |
          git checkout -- ${FLATPAK_ID}.yml

      - name: Recheck and open PR
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: ${{ env.GIT_USER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ env.GIT_USER_EMAIL }}
          EMAIL: ${{ env.GIT_USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork ${{ env.FLATPAK_ID }}.yml
